DROP TABLE BLOG;

CREATE TABLE BLOG(
	URL VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	POSTDATE DATE,
	THUMBNAIL VARCHAR2(1000),
	CONSTRAINT BLOG_PK PRIMARY KEY(URL)
);

SELECT * FROM BLOG;
