DROP SEQUENCE FATSEQ;
DROP TABLE FAQ;

CREATE SEQUENCE FAQSEQ NOCACHE;

CREATE TABLE "FAQ" (
   "FAQNO" NUMBER,
   "TITLE" VARCHAR2(100) NOT NULL,
   "CONTENT" VARCHAR2(4000) NOT NULL,
   PRIMARY KEY ("FAQNO")
);

SELECT * FROM FAQ;