<<<<<<< HEAD
=======
DROP TABLE HISTORY;
>>>>>>> branch 'master' of https://github.com/junmipark/Uravel_TeamProject.git

CREATE TABLE HISTORY (
  "HISTORYNO" NUMBER NOT NULL,
  "TRAVELNO" NUMBER REFERENCES TRAVEL(TRAVELNO),
  "TRAVELNAME" VARCHAR2(100) REFERENCES TRAVEL(TRAVELNAME),
  "DESCRIPTION" VARCHAR2(4000) NOT NULL,
  "URL_PIC1" VARCHAR2(500) NOT NULL,
  "URL_PIC2" VARCHAR2(500),
  "SOURCE" VARCHAR2(1000) NOT NULL,
  PRIMARY KEY ("HISTORYNO")
);

SELECT * FROM HISTORY;
