
DROP TABLE INQUIRY;

CREATE TABLE "INQUIRY" (
   "INQNO" NUMBER NOT NULL,
   "GROUPNO" NUMBER NOT NULL,
   "USERNO" NUMBER NOT NULL,
   "QUE_TYPE" VARCHAR2(500) NOT NULL,
   "TITLE" VARCHAR2(1000) NOT NULL,
   "CONTENT" VARCHAR2(2000) NOT NULL,
   "POSTDATE" DATE,
   PRIMARY KEY ("INQNO")
);

DROP SEQUENCE INQSEQ;
DROP SEQUENCE INQ_G_SEQ;
DROP TABLE INQUIRY;

CREATE SEQUENCE INQSEQ NOCACHE;
CREATE SEQUENCE INQ_G_SEQ NOCACHE;

CREATE TABLE "INQUIRY" (
   "INQNO" NUMBER NOT NULL,
   "GROUPNO" NUMBER NOT NULL,
   "USERNO" NUMBER REFERENCES MEMBER(USERNO),
   "QUE_TYPE" VARCHAR2(500) NOT NULL,
   "TITLE" VARCHAR2(1000) NOT NULL,
   "CONTENT" VARCHAR2(2000) NOT NULL,
   "POSTDATE" DATE,
   PRIMARY KEY ("INQNO")
);

ALTER TABLE INQUIRY ADD STATUS VARCHAR2(10) DEFAULT 'FALSE';