CREATE TABLE LIKE_COUNT(
   "USERNO" NUMBER REFERENCES MEMBER(USERNO),
   "TRAVELNO" NUMBER REFERENCES TRAVEL(TRAVELNO),
   "LIKE_COUNT" NUMBER DEFAULT 0
);

SELECT * FROM LIKE_COUNT;

DROP TABLE LIKE_COUNT;

SELECT * FROM TAB;