DROP TABLE LIKE_COUNT;

CREATE TABLE LIKE_COUNT(
	"USERNO" NUMBER REFERENCES MEMBER(USERNO),
	"TRAVELNO" NUMBER REFERENCES TRAVEL(TRAVELNO),
);

SELECT * FROM LIKE_COUNT;

ALTER TABLE LIKE_COUNT DROP COLUMN LIKE_COUNT;
