DROP TABLE LOCATION;

CREATE TABLE "LOCATION" (
  "LOCALCODE" NUMBER,
  "LOCALNAME" VARCHAR2(20) UNIQUE NOT NULL,
  PRIMARY KEY ("LOCALCODE")
);

INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (1,'강남구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (2,'강동구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (3,'강북구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (4,'강서구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (5,'관악구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (6,'광진구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (7,'구로구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (8,'금천구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (9,'노원구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (10,'도봉구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (11,'동대문구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (12,'동작구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (13,'마포구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (14,'서대문구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (15,'서초구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (16,'성동구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (17,'성북구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (18,'송파구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (19,'양천구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (20,'영등포구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (21,'용산구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (22,'은평구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (23,'종로구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (24,'중구');
INSERT INTO LOCATION (LOCALCODE,LOCALNAME) VALUES (25,'중랑구');

SELECT * FROM LOCATION;

CREATE TABLE USERLOCAL(
   USERNO NUMBER REFERENCES MEMBER(USERNO),
   LOCALCODE NUMBER REFERENCES "LOCATION"("LOCALCODE")
);