DROP TABLE NOTICE;
DROP SEQUENCE NOTICESEQ;

CREATE SEQUENCE NOTICESEQ NOCACHE;

CREATE TABLE "NOTICE" (
	"NOTICENO" NUMBER,
	"TITLE" VARCHAR2(1000) NOT NULL,
	"CONTENT" VARCHAR2(4000) NOT NULL,
	"POSTDATE" DATE,
	PRIMARY KEY ("NOTICENO")
);

SELECT * FROM "NOTICE";

/*
 * ORACEL SEQUENCE에 NO CACHE를 설정해야하는 이유 : https://blog.daum.net/lokkentech83/25
 */