DROP TABLE REVIEW;
DROP SEQUENCE POSTNOSEQ;

CREATE SEQUENCE POSTNOSEQ NOCACHE;
DROP TABLE USER;
CREATE TABLE MEMBER( 
	USERNO NUMBER PRIMARY KEY,
	USERID VARCHAR2(20),
	USERPW VARCHAR2(20) NOT NULL,
	USERNAME VARCHAR2(50) NOT NULL,
	BIRTH DATE,
	EMAIL VARCHAR2(100) NOT NULL,
	PHONE VARVHAR2(20), 
	ROLE CHAR(10) CHECK(ROLE IN ('ADMIN','USER')),
	ENABLED CHAR(3) CHECK(ENABLED IN ('Y','N'))
 );
 DROP TABLE MEMBER;
 CREATE TABLE MEMBER (
  USERNO NUMBER,
  USERID VARCHAR2(20),
  USERPW VARCHAR2(20) NOT NULL,
  USERNAME VARCHAR2(50) NOT NULL,
  BIRTH DATE,
  EMAIL VARCHAR2(100) NOT NULL,
  PHONE VARCHAR2(20),
  ROLE VARCHAR2(10) CHECK(ROLE IN ('ADMIN','USER')),
  ENABLED VARCHAR2(2) CHECK(ENABLED IN('Y','N')),
  PRIMARY KEY(USERNO), UNIQUE(USERID)
);

DROP TABLE LOCATION;

CREATE TABLE "LOCATION" (
  "LOCALCODE" NUMBER,
  "LOCALNAME" VARCHAR2(20) UNIQUE NOT NULL,
  PRIMARY KEY ("LOCALCODE")
);

CREATE TABLE "THEME" (
  "THEMECODE" NUMBER,
  "THEMENAME" VARCHAR2(20) UNIQUE NOT NULL,
  PRIMARY KEY ("THEMECODE")
);

CREATE TABLE "TRAVEL" (
  "TRAVELNO" NUMBER ,
  "TRAVELNAME" VARCHAR2(100) NOT NULL,
  "LOCALCODE" NUMBER NOT NULL,
  "THEMECODE" NUMBER NOT NULL,
  "ADDRESS" VARCHAR2(1000) NOT NULL,
  "DESCRIPTION" VARCHAR2(4000) NOT NULL,
  "URL_PIC" VARCHAR2(500),
  PRIMARY KEY ("TRAVELNO"),
  UNIQUE("TRAVELNAME"),
  FOREIGN KEY ("LOCALCODE") REFERENCES LOCATION("LOCALCODE"),
  FOREIGN KEY ("THEMECODE") REFERENCES THEME("THEMECODE")
);



CREATE TABLE REVIEW(
	POSTNO NUMBER NOT NULL,
	USERNO NUMBER REFERENCES MEMBER(USERNO) NOT NULL,
	POSTDATE DATE NOT NULL,
	TRAVELNO NUMBER REFERENCES TRAVEL(TRAVELNO) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	CONSTRAINT REVIEW_PK PRIMARY KEY(POSTNO)
    );
    
SELECT * FROM REVIEW;

SELECT * FROM TAB;