DROP TABLE REVIEW;
DROP SEQUENCE POSTNOSEQ;

CREATE SEQUENCE POSTNOSEQ NOCACHE;

CREATE TABLE REVIEW(
	POSTNO NUMBER NOT NULL,
	USERNO NUMBER REFERENCES MEMBER(USERNO) NOT NULL,
	POSTDATE DATE NOT NULL,
	TRAVELNO NUMBER REFERENCES TRAVEL(TRAVELNO) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	CONSTRAINT REVIEW_PK PRIMARY KEY(POSTNO)
    );
    
SELECT * FROM REVIEW;
