DROP TABLE REVIEW;
DROP SEQUENCE POSTNOSEQ;

CREATE SEQUENCE POSTNOSEQ NOCACHE;

CREATE TABLE REVIEW(
	POSTNO NUMBER NOT NULL,
	USERNO NUMBER REFERENCES MEMBER(USERNO) NOT NULL,
	POSTDATE DATE NOT NULL,
	TRAVELNO NUMBER REFERENCES TRAVEL(TRAVELNO) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	CONSTRAINT REVIEW_PK PRIMARY KEY(POSTNO)
    );
    
ALTER TABLE REVIEW ADD (FILENAME VARCHAR2(200));
ALTER TABLE REVIEW ADD (FILESIZE NUMBER);
ALTER TABLE REVIEW ADD (LOCALNAME VARCHAR2(20));
ALTER TABLE REVIEW ADD (THEMENAME VARCHAR2(20));

ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_FK FOREIGN KEY(LOCALNAME) REFERENCES LOCATION(LOCALNAME);
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_FK1 FOREIGN KEY(THEMENAME) REFERENCES THEME(THEMENAME);


SELECT * FROM REVIEW ORDER BY POSTNO;
