DROP TABLE TRAVEL;

CREATE TABLE "TRAVEL" (
  "TRAVELNO" NUMBER ,
  "TRAVELNAME" VARCHAR2(100) NOT NULL,
  "LOCALCODE" NUMBER NOT NULL,
  "THEMECODE" NUMBER NOT NULL,
  "ADDRESS" VARCHAR2(1000) NOT NULL,
  "DESCRIPTION" VARCHAR2(4000) NOT NULL,
  "URL_PIC" VARCHAR2(500),
  PRIMARY KEY ("TRAVELNO"),
  UNIQUE("TRAVELNAME"),
  FOREIGN KEY ("LOCALCODE") REFERENCES LOCATION("LOCALCODE"),
  FOREIGN KEY ("THEMECODE") REFERENCES THEME("THEMECODE")
);

SELECT * FROM TRAVEL;
