DROP TABLE TRAVEL;

CREATE TABLE "TRAVEL" (
  "TRAVELNO" NUMBER ,
  "TRAVELNAME" VARCHAR2(100) NOT NULL,
  "LOCALCODE" NUMBER NOT NULL,
  "THEMECODE" NUMBER NOT NULL,
  "ADDRESS" VARCHAR2(1000) NOT NULL,
  "DESCRIPTION" VARCHAR2(4000) NOT NULL,
  "URL_PIC" VARCHAR2(500),
  PRIMARY KEY ("TRAVELNO"),
  UNIQUE("TRAVELNAME"),
  FOREIGN KEY ("LOCALCODE") REFERENCES LOCATION("LOCALCODE"),
  FOREIGN KEY ("THEMECODE") REFERENCES THEME("THEMECODE")
);

<<<<<<< HEAD
CREATE SEQUENCE travelseq START WITH 122;

DROP TABLE TRAVEL;

SELECT *
FROM tab;

INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (1,'구스테이크528',1,3,'서울 강남구 압구정로 108','숙성한 소고기 스테이크를 먹을 수 있는 곳으로 유명해졌다.','https://drive.google.com/uc?export=view&id=1chqMi9TC3OhkD6Do8tAktHFkorOemRGU');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (2,'부산양곱창',1,3,'서울 강남구 언주로98길 8-1','비교적 저렴하게 곱창을 즐길 수 있다.','https://drive.google.com/uc?export=view&id=1reUmAXyZ5S6GGyKhuNuckrGjs8jRtEf0');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (3,'스시 카이신',1,3,'서울 강남구 도산대로100길 12','작고 아담한 스타일의 고급 스시 전문점이다.','https://drive.google.com/uc?export=view&id=1kcgVwqlrtL3FqFrVkU58jWfZVGTSuNsT');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (4,'그란구스또',1,3,'서울 강남구 삼성로 340 1,2층','해물을 위주로 한 정통 이탈리아 코스 요리를 맛볼 수 있는 곳이다.','https://drive.google.com/uc?export=view&id=1hj5In-s2mMuETTcZWOpvHHOf7lSYBWDU');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (5,'임피리얼 팰리스 서울',1,10,'서울 강남구 언주로 640','서울 강남에 위치한 5성급 호텔','http://drive.google.com/uc?export=view&id=1KhvW2CtvLHn4LIJiwRU-7wGLMnn_bWo9');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (6,'선정릉(선릉과 정릉)',1,6,'서울 강남구 선릉로100길 1','  선릉은 9대 성종과 부인 정현왕후의 무덤이다.
  성종은 유교사상을 정착하여 왕도정치를 실현하고자 사림을 성장시켜 훈구세력을 견제하고, 정치기반을 조성함으로써 조선 초기의 전반적인 체제를 안정시켰다.
  선릉은 왕릉과 비릉이 각각 다른 산등성이에 있는 동원이강의 형식으로 비릉에는 병풍석을 세우지 않았고, 다른 석물들은 왕릉과 같으며 『국조오례의』를 따르고 있다. 왕릉에는 12면의 병풍석을 세우고 그안에 동물의 머리에 사람의 모습을 한 십이지신상을 새겼다. 난간석은 12칸이며 그 밖에 양석·호석·망주석·문석인 등의 석물이 있다. 
  정릉은 11대 중종의 무덤이다.
  중종은 연산군의 잘못된 정치를 바로 잡기위해 노력하였으나, 개혁파와 공신파의 정치적 논쟁이 끊이지 않아 조정이 안정되지 못하였다.
  정릉은 원래 중종의 두번째 왕비(제1계비) 장경왕후의 무덤인 희릉의 오른쪽 언덕에 있었으나 세번째 왕비(제2계비)인 문정왕후 윤씨가 풍수지리상 불길하다고 하여 현재의 자리로 옮겼다. 무덤 주변의 석물은 선릉의 석물제도를 본떴다. 조선왕릉 중 왕만 단독으로 있는 무덤은 후대에 왕릉이 된 단종의 장릉을 제외하고 태조의 건원릉과 중종의 정릉뿐이다.
  임진왜란 때는 선·정릉의 양릉이 훼손되는 변을 겪게 된다. 재실(齋室)은 양릉의 사이에 있으며, 여름철의 침수를 피하기 위해 층단에 지었는데 이러한 예는 선릉·정릉 뿐이다.','http://www.heritage.go.kr/unisearch/images/history_site/2021071211001301.jpg, http://www.heritage.go.kr/unisearch/images/history_site/2021071211001302.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (7,'노보텔 앰배서더 서울 강남 호텔',1,10,'서울 강남구 봉은사로 130','서울 강남에 위치한 4성급 호텔','http://drive.google.com/uc?export=view&id=1R9PmGV0YZtW2uaEzTZgs_F3m-VdupHb2');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (8,'더 그린테이블',1,3,'서울 강남구 선릉로155길 13','캐주얼한 비스트로 스타일의 프랑스 음식을 맛볼 수 있다.','https://drive.google.com/uc?export=view&id=1CUamKCRPiNaAS0JtlUdwePnIkJjd29tc');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (9,'강동그린웨이 가족캠핑장',2,9,'서울 강동구 둔촌동 562','가족친화적 캠핑장이다','http://drive.google.com/uc?export=view&id=1YUeP4s1DrTe3cpvXZbLhE6evWD1dlbEy');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (10,'솔밭근린공원',3,1,'서울 강북구 삼양로 561','솔밭근린공원은 강북구 우이동에 위치한 소나무 숲공원이다.','http://drive.google.com/uc?export=view&id=1tkuAew63dzUxD1JD74TLmvbzt2F-6Hww');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (11,'봉제산 둘레길',4,4,'서울 강서구 화곡동','사색의 공간, 오리나무쉼터, 무궁화공원 등 북카페를 거닐며 봉제산만의 고유한 생태와 역사문화 경관을 탐방할 수 있음','https://gil.seoul.go.kr/view/point/2013/09/26/10558094196172.JPG');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (12,'고드니',4,8,'서울 강서구 마곡중앙로 161-1 캐슬파크 2F 220호','마곡나루 힙한 비건카페','https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=https%3A%2F%2Fmyplace-phinf.pstatic.net%2F20210922_275%2F1632284038913jz2rU_JPEG%2Fupload_97e117d1040ec9c944803659e041a6a9.jpeg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (13,'매화근린공원',4,1,'서울 강서구 등촌1동 630-13 ','조경시설이 주를 이루며 각종 편의시설이 마련','http://drive.google.com/uc?export=view&id=1ZoIexEVWsFGn40bg2gWgZ-iShTCE8kv-');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (14,'소악루',4,6,'서울 강서구 양천로47나길 52-54','  소악루는 양천향교 뒷산인 궁산 기슭에 있는 정자이다. 예부터 소악루에서 바라보는 한강 변의 뛰어난 절경으로 문인들의 풍류의 장이었으며 겸재 정선이 그린 진경산수화를 토대로 한강을 조망할 수 있게 복원했다.
  1737년(영조 13) 동복현감을 지낸 이유(李楡, 1675~1757)가 경관과 풍류를 즐기기 위해 자신의 집 부근 옛 악양루 터에 지었다. ‘소악루’란 중국 동정호의 웨양루〔岳陽樓〕경치와 버금가는 곳이라 하여 붙인 이름이다.
  당초 가양동 세숫대바위 근처에 세운 원 건물은 화재로 소실되었다. 1994년 5월 구청에서 한강 변 경관 조성과 조망을 고려하여 현 위치에 신축했다. 건물은 정면 3칸 측면 2칸의 규모로서 화강석 8각 주춧돌에 민흘림 원기둥을 세운 5량집 겹처마 구조이다. 지붕은 단층 팔작지붕이며 주위에는 조망하기 좋게 난간을 둘러놓았다.','https://mediahub.seoul.go.kr/wp-content/uploads/editor/images/000273/6_1.jpg, https://mediahub.seoul.go.kr/wp-content/uploads/editor/images/000273/1_3.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (15,'별빛내린천',5,4,'서울 관악구 신림동 808-1','도림천에서 별빛내림천은으로 변경됐으며 산책로, 자전거도로, 벽천분수, 물놀이장, 야외무대 등의 주요시설로 구성 됨','https://img8.yna.co.kr/etc/inner/KR/2021/03/26/AKR20210326041700004_01_i_P4.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (16,'온고지신',5,8,'서울 관악구 관악로14길 101 온고지신','"옛것을 익히고 그것을 미루어서 새것을 앎" 모토로 옛것과 현대를 아울어 블렌딩 차와 밀크티 제조','https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMDEwMTRfMjc5%2FMDAxNjAyNjg1NjMyMDg2.xZKABURKSgdnC07JeLVjqAMjZqErMyMGx2QXFLFbTo8g.j62FWve6Brh7YGUjazrdSXBGNIQOANd-MLo-iWSL_CIg.JPEG.lael_v_v%2FIMG_9212.jpg&type=sc960_832');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (17,'바달비',5,3,'서울 관악구 봉천로12길 17','"넓은 들"이란 뜻을 가진 한정식 전문점','https://drive.google.com/uc?export=view&id=11GWUVJiVncbzK7ZeoeZMWXgS93MiPgD5');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (18,'그랜드 워커힐 서울',6,10,'서울 광진구 워커힐로 177','광진구에 위치한 5성급 호텔','http://drive.google.com/uc?export=view&id=1qDgyryWHVIWHTaNU3h8fZqgYk8Bi6lWw');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (19,'버글러커피바',6,8,'서울 광진구 천호대로127길 74 1층','째즈와 클래식도 함께 즐길 수 있는 감성 커피전문점','https://modo-phinf.pstatic.net/20210610_121/1623305147968SjENU_JPEG/mosaqnFEam.jpeg?type=w1100');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (20,'어린이 대공원',6,1,'서울 광진구 능동로 216, 서울어린이대공원','가족단위의 휴식공간','http://drive.google.com/uc?export=view&id=1F4BDQEsk1y70-5y4VVIgs2WB-GZEk161');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (21,'질문서점 인공위성',7,7,'서울 구로구 구로중앙로 27가길 32','책과 그 책을 기부한 기부자의 질문 및 인터뷰가 적힌 종이로 리패키징하여 진열한 것이 특징인 서점','http://mediahub-corona19.seoul.go.kr/wp-content/uploads/2019/07/ae684fc72c2f85207129603e88617f6a.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (22,'천왕산 가족캠핑장',7,9,'서울 구로구 연동로12길 149','천왕산 입구에 위치한 가족 친화적 컨셉의 캠핑장','http://drive.google.com/uc?export=view&id=1f-YYgswR0iZ6mutrGQsvpTrd51q8tMrV');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (23,'라운지엑스',7,8,'서울 구로구 구로중앙로 152','로봇과 바리스타가 협업하여 핸드드립 알고리즘을 통해 커피 제공','https://loungeshop.co.kr/file_data/loungex/2020/12/24/5cc2adac991e4b539f41f0fb5edd8362.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (24,'노보텔 앰버서더 독산',8,10,'서울시 금천구 시흥대로 378','금천구에 위치한 4성급 호텔','http://drive.google.com/uc?export=view&id=1EfkjC6wwG6vAXcGQllLRp2HHRdx7oxSh');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (25,'감로천 생태공원',8,1,'서울 금천구 독산로54길 188',' 다양한 나무와 꽃·풀·곤충 등의 자연 생태를 관찰할 수 있는 금천구의 자랑거리','http://drive.google.com/uc?export=view&id=1PMWCUtKIGxO7BVoBEr8XANBMDGGtIj53');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (26,'라라브레드',9,8,'서울 노원구 공릉로41길 32','신선한 재료를 이용해 브런치와 디저트가 많은 카페 특히 오픈샌드위치가 맛있음','https://lalabread.co.kr/web/upload/moen/d_img/brand_01.jpg
%EC%84%9C%EC%9A%B8%EB%85%B8%EC%9B%90%EA%B5%AC%EC%B9%B4%ED%8E%98/place/1062761073?
placePath=%3Fentry%253Dpll&c=14145310.6438622,4526565.1741050,15,0,0,0,dh');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (27,'불암산',9,2,'서울 노원구 상계동','능선이 길게 뻗어 있어 시원한 경치를 볼 수 있음','http://drive.google.com/uc?export=view&id=1648xOV1ozN1IaUNZP2sOZzrZRL0f96SV');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (28,'수락산',9,2,'서울 노원구 상계동','서울의 수호산, 산 전체가 석벽과 암반으로 구성되어 있어 난이도 높은 산','http://drive.google.com/uc?export=view&id=1fstZTFkSPrZm8o0DP9fpeK_EkXTXK8yC');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (29,'영축산순환산책로',9,4,'서울 노원구 월계동 산 130-3','안전 난간도 설치해 장애인 등 보행약자뿐 아니라 남녀노소 누구나 숲길을 따라 사색과 힐링이 가능한 산책로','https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA1MDJfMTMg%2FMDAxNjE5OTQ1Njg5NTAw.uLRW4_nnKM_CvprPX0wIiITQWsdj8iJgSGaNjn4oPYMg.tzGKwpJ3dX5w-o6exan62xTrZV0zED4habsNlEde61kg.JPEG.skjh630%2F%25BF%25B5%25C3%25E0%25BB%25EA001.jpg&type=sc960_832');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (30,'태강릉(태릉과 강릉)',9,6,'서울 노원구 화랑로 727','  태릉은 조선 제11대 중종(재위 1506∼1544)의 세번째 왕비인 문정왕후 윤씨(1501∼1565)의 무덤이다.
  본관은 파평으로 중종의 두번째 왕비인 장경왕후가 1515년 죽자 1517년에 17세의 나이로 왕비가 되었다. 중종이 있는 정릉에 묻히려 하였으나 장마철 침수로 인하여 이곳에 묻히게 되었다. 무덤은 십이지신과 구름무늬가 새겨진 12면으로 된 병풍석이 둘러져 있다. 무덤 앞에는 상석·망주석 등이 『국조오례의』에 따라 제작되었다.
  무덤 아래에는 한국 전쟁시 훼손되었다가 1995년 다시 지은 정자각이 있다. 사람모양의 돌조각상(석인)은 4등신으로 입체감이 표현되지 않았는데, 당시 석인의 특징을 보여준다.
  강릉은 조선 제13대 명종(재위 1545∼1567)과 그의 부인인 인순왕후 심씨(1532∼1575)의 무덤이다.  태릉과 같은 병풍석이 둘러져 있다.','http://www.heritage.go.kr/unisearch/images/history_site/2021071308524003.jpg, http://www.heritage.go.kr/unisearch/images/history_site/2021071308524500.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (31,'초안산캠핑장',9,9,'서울 노원구 마들로5가길 66-107','초안산캠핑장, 산 바로 앞에 위치해있다','http://drive.google.com/uc?export=view&id=1b1DS343TyagiCHS1TmmgN_8kKl942UkQ');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (32,'도봉산',10,2,'서울 도봉구 도봉동','풍경이 워낙 아름다워 ''에덴의 동산'' 이라고 불린다','http://drive.google.com/uc?export=view&id=14G7xf4xUcrZUGdQBj2_A430yPYH2CIXk');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (33,'원당샘공원',10,4,'서울 도봉구 해등로32가길 16 (우)01360','600년 전부터 마을의 생활용수로 공급되던 원당샘을 복구하여 조성한 공원으로 역사와 문화가 어우러지는 도봉구 문화명소','https://tour.dobong.go.kr/Open_content/images/new_SRIFRI_A1_00060_1.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (34,'무수울',10,8,'서울 도봉구 도봉로173길 124','도봉산 무수골 계곡에 허름한 작은 카페, 스페셜 커피 원두 사용','https://modo-phinf.pstatic.net/20210827_123/16300286917232DvQX_JPEG/mosaLCVFpA.jpeg?type=w720');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (35,'서울약령시 한의약박물관',11,6,'서울 동대문구 약령중앙로 26 서울한방진흥센터','우리나라 최대 한약 유통시장인 약령시에 있는 한의약 박물관은 한의약의 계승과 발전을 위해 다양한 자료를 수집 및 관리, 보존하고 있다. 또한, 한의약의 역사를 비롯해 여러 한약재의 실물 전시를 마련해 한의약에 대한 정보 제공 및 이해를 돕고 있다.  ','https://cdn.sisanews.kr/news/photo/202007/51380_37058_016.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (36,'지금의 세상',12,7,'서울 동작구 동작대로 3길 41','시·소설 등의 장르가 아닌, ‘행복에 대한 갈망’ ‘미래에 대한 두려움’ ‘지적 호기심’ ‘사랑에 대한 감정’ ‘마음의 편안함’이라는 다섯 개의 테마로 책을 분류한 개성있는 큐레이션이 특징인 서점','https://topclass.chosun.com/news_img/1910/1910_040_7.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (37,'현충원 나들길',12,4,'서울 동작구 사당동','국가에 공이 있는 사람의 유골 또는 시신을 안장한 국립현충원을 도는 산책로','https://search.pstatic.net/common/?src=http%3A%2F%2Fpost.phinf.naver.net%2FMjAxNzA3MjBfMzUg%2FMDAxNTAwNTM2MTA1OTk2.nqcIM_jeGSgbtUPzj96Obpvsn7n9GLhzY-syVzG1uRYg.JF8imk80cWkOA_9I7thXppWrXweFZtgLyKDJyJTwtX0g.JPEG%2FIywwiVDDdD7t9t7eoK5Q1_Ml8YdA.jpg&type=sc960_832');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (38,'보라매공원',12,1,'서울 동작구 여의대방로20길 33','잘 정돈된 나무, 꽃, 그리고 깨끗한 거리들로 산책하기 좋음','http://drive.google.com/uc?export=view&id=127D08mpYWKMRZEGcO1wmQ9IOfIF8r7HG');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (39,'문화비축기지 산책',13,4,'서울 마포구 증산로 87','폐산업시설을 재생하여 역사적 의미를 보존, 시민들의 휴식과 다양한 커뮤니티 활동 가능 공간','https://image.dnews.co.kr/photo/photo/2018/03/23/201803231015186250850-2-105699.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (40,'하늘공원 야경',13,5,'서울 마포구 하늘공원로 95','억새와 노을, 야경으로 유명한 난지캠핑장 옆에 위치한 생태환경공원','http://www.newsinside.kr/news/photo/201710/475571_319948_4453.JPG');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (41,'문화비축기지',13,6,'서울 마포구 증산로 87','  마포구 서울월드컵경기장 인근 매봉산에 에워싸인 ‘문화비축기지’는 일반인의 접근과 이용이 철저히 통제됐던 산업화시대 유산인 마포 석유비축기지가 도시재생을 통해 시민 품으로 돌아오게 된 문화공원이다.
  1973년 석유파동 이후 76~78년에 5개 탱크를 건설해 당시 서울시민이 한 달 정도 소비할 수 있는 양인 6,907만 리터의 석유를 보관했던 마포석유비축기지는 2002년 월드컵을 앞두고 안전상의 이유로 폐쇄됐는데, 10년 넘게 활용방안을 찾지 못하다가 지난 2013년 시민아이디어공모를 통해 문화비축기지로의 변신을 결정했다.
  당시 석유를 보관하던 탱크들은 석유 대신 매일 색다른 문화를 창출하는 문화탱크로 역할이 바뀌었다. 기존 5개의 탱크는 열린 문화 공간으로 탈바꿈하였고, 해체된 탱크의 철판을 활용해 만들어진 T6는 시민들의 커뮤니티 공간이 되었다. 비어있던 야외 공간은 아이들이 뛰어놀 수 있는 문화 마당으로 만들었다. 부지에 남아있던 수림은 최대한 보존하고 다양한 종류의 꽃과 나무를 심어 공원으로 조성했다. 매봉산으로 이어지는 산책로에서는 종종 산토끼와 청설모도 만날 수 있다.','https://flexible.img.hani.co.kr/flexible/normal/715/536/imgdb/original/2020/0212/20200212503109.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (42,'상암 하늘공원',13,1,'서울 마포구 하늘공원로 95','서울 억새 명소이자 다양한 꽃 구경하기 좋은 공원','http://drive.google.com/uc?export=view&id=1RhrMRKkvVW9Q-n_XTh-hnT8kpAkatEoX');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (43,'성산왕갈비',13,3,'서울 마포구 월드컵북로 233','푸짐한 생돼지갈비로 유명하다.','https://drive.google.com/uc?export=view&id=13Jk9MnRv_FtHKLpcNMoV47xhkusn2A-F');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (44,'난지캠핑장',13,9,'서울 마포구 한강난지로 28','한강에 있는 난지캠핑장, 한강과 매우 근접해있다','http://drive.google.com/uc?export=view&id=15qUbOSVef5S6d0jMfmE2eZF_Ayn-DHtx');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (45,'노을캠핑장',13,9,'서울 마포구 하늘공원로 108-1','난지캠핑장과 매우 가까운 한강에 근접한
노을 캠핑장','http://drive.google.com/uc?export=view&id=1g1uVtBp7QKesZL_ESFVvuhIkU_4AN9Ec');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (46,'한국영상자료원',13,6,'서울 마포구 월드컵북로 400','  한국영상자료원은 국내외 영화 필름과 함께 다양한 비필름 자료들(비디오물, 오디오물, 포스터, 스틸, 시나리오, 도서, 정기간행물, 의상, 소품, 영화인 애장품)를 포함하여 모든 영상자료를 수집하고 있다. 영화 필름은 극영화와 함께 뉴스릴, 기록물 등의 비극영화까지, 다양한 규격의 필름부터 최근 디지털 파일까지 모두 수집 대상이 된다. 한국영상자료원은 국내 뿐 아니라 해외에 산재되어있는 영상자료들 역시 적극적으로 발굴, 수집하고 있으며, 최근에는 이규환 감독의 <해연>(1948)을 일본 고베영화자료관에서 복사 수집한 바 있다.','http://cdn.econovill.com/news/photo/201809/346849_221454_448.jpg, http://cdn.econovill.com/news/photo/201809/346849_221456_449.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (47,'스프링 플레어',13,7,'서울 마포구 동교로 27길','예술 관련 서적을 중심으로하여 라이프스타일, 반려, 일, 여행, 태도, 인생 등의 키워드로 선별된 다양한 책을 판매하는 ''일상예술서점''','http://image.yes24.com/images/chyes24/1/0/8/e/108e50b22fe4756a774207e718611456.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (48,'(구)서대문형무소',14,6,'서울 서대문구 통일로 251','  일본이 우리나라에 대한 침략을 본격화하기 위해 1907년 인왕산 기슭에 일본인이 설계하여 건립한 근대적인 감옥이다.
  약 500여 명을 수용할 수 있는 560여 평의 목조건물을 짓고 ‘경성감옥’이라 불렀다. 종로의 감옥에서 500여 명을 데려와 수용하고 광복을 맞이하는 1945년까지 독립운동가들을 가두고 고문과 박해를 하고 심지어 목숨을 빼앗은 곳이다. 애국인사들이 늘어나자 1912년 일제는 마포구 공덕동에 감옥을 또 지어 경성감옥이라 하고, 원래의 경성감옥은 서대문감옥이라 불렀다. 1923년 서대문감옥은 서대문형무소로 바뀌었고 1944년에는 2,890명이 수용되었다. 18세 미만의 소녀들과 10년 이상을 선고받은 자, 그리고 무기수까지 수용하였으며, 김구선생·강우규·유관순 열사 등이 이곳에 수감되었었다.  유관순 열사는 이 곳에서 목숨을 다하였다.
  1946년 광복 직후에는 경성형무소·서울형무소로 바뀌고, 반민족행위자와 친일세력들이 수용되었다. 1961년에는 서울교도소로, 1967년에는 서울구치소로 바뀌었고, 4·19혁명과  5·16군사쿠데타와 같은 정치적 변동으로 인해 많은 시국사범들이 수감되었다. 1988년에 사적지로 지정되었다. 
  일제강점기에는 민족독립의 역사를 지니며 그후로는 민주화와 정치적 변화의 모습을 간직한 곳으로서 후손들에게 민족의 자존과 자주정신을 일깨워주는 산 교육장으로 매우 뜻깊은 곳이다.','http://www.heritage.go.kr/unisearch/images/history_site/202104151023470a.JPG, http://www.heritage.go.kr/unisearch/images/history_site/2021041510234705.JPG');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (49,'안산',14,2,'서울 서대문구 현저동','아름다운 곡선으로 굽이치고 있는 한강을 내려다보는 풍경이 일품','http://drive.google.com/uc?export=view&id=1f5HXWfJoUcllAq8MOjxQBQXoT4_eCUSk');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (50,'반표대교 야경',15,5,'서울특별시 서초구 올림픽대로 2085-14','용산구와 서초구를 잇는 2층 교량으로 무지개 분수 쇼 및 여의도 불꽃축제 기간에 불꽃 놀이를 구경할 수 있는 관광 명소','https://live.staticflickr.com/5598/15354504160_f0997ae50f_b.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (51,'양재시민의 숲',15,1,'서울 서초구 매헌로 99 (양재동)','나무들의 천국, 맨발공원 등이 있음','http://drive.google.com/uc?export=view&id=1Dm2fdmrAQ9ojqKfeG1p4bbnbZHepAa13');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (52,'서울서초글램핑청계산장',15,9,'서울 서초구 청계산로 140-94','청계산에 위치한 산장인데, 글램핑이 주 컨셉인
캠핑장이다','http://drive.google.com/uc?export=view&id=194rUF30q5JCocp35ZmFmp0EgRVsrEbU-');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (53,'잠원한강공원 여름캠핑장',15,9,'서울 서초구 잠원로 221-124','한강기슭에 위치한 캠핑장이다','http://drive.google.com/uc?export=view&id=1ECwkf_V9zfKSMnhq1ZFUEb_UMQTkBq5C');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (54,'헌인릉(헌릉과 인릉)',15,6,'서울 서초구 헌인릉길 36-10','  헌릉은 조선 3대 태종(재위 1400∼1418)과 원경왕후 민씨(1365∼1420)의 무덤이다.
  태조 이성계의 다섯번째 아들로서 아버지를 도와 조선왕조를 세웠다. 1·2차 왕자의 난을 진압하고 정종 2년(1400)에 왕위를 물려받았다. 토지와 조세제도를 정비하고 군사제도도 개혁하였으며, 유교를 숭상하고 불교를 억압하는 등 국정전반에 대한 개혁을 단행하여, 조선 초기의 민생안정을 이룩하였다. 태종의 부인인 원경왕후 민씨는 여흥부원군 민제의 딸이며, 태종이 왕위에 오르기까지 큰 힘이 되었다.
  헌릉은 쌍릉으로 무덤 아랫부분이 병풍석으로 둘러있으며, 무덤의 형식은 태조의 건원릉을 따랐다. 각 무덤에 12칸의 난간석을 둘러서 서로 연결하였고 무덤 앞에는 양석과 호석·문석인·마석을 배치하였다. 무덤 앞의 석물은 고려시대의 현릉·정릉, 조선시대의 후릉과 같이 망주석을 제외하고는 각각 하나씩을 더 갖추었다. 언덕 아래에는 정자각이 있고 비각을 세웠다. 
  인릉은 23대 순조(재위 1800∼1834)와 순원왕후 김씨(1789∼1857)의 무덤이다. 순조는 11세에 왕위에 올랐으나 나이가 어려서 대왕대비인 정순왕후 김씨에게 정치를 돌보게 됨으로써 외척에 의한 정치가 극에 달하였고, 사회가 혼란했다.
  인릉은 무덤에 병풍석을 세우지 않았고, 12칸의 난간석을 둘렀으며 양석과 마석·상석·망주석을 세웠다. 언덕 아래에는 2개의 비석을 세웠다.','http://www.heritage.go.kr/unisearch/images/history_site/2021070714551501.jpg, http://www.heritage.go.kr/unisearch/images/history_site/2021070816265101.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (55,'응봉산 야경',16,5,'서울 성동구 독서당로 362','한강, 롯데월드타워, 청계산, 관악산의 경관을 한눈에 볼 수 있는 야경 명소','https://www.kfoodtimes.com/news/photo/202010/13230_23817_5934.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (56,'응봉산',16,2,'서울 성동구 금호동4가 1540','주변 풍경이 매우 아름다움','https://drive.google.com/file/d/1iPRNWdTsP2Jazd-bfL_pznj7srHt7tBd/view?usp=sharing');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (57,'카모메 그림책방',16,7,'서울 성동구 무수막길 84','타로를 통해 고객에게 맞는 그림책을 추천하는 그림 책방','https://cphoto.asiae.co.kr/listimglink/1/2020040316300258724_1585899003.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (58,'길상사',17,6,'서울 성북구 선잠로5길 68','  길상사는 1997년 12월에 창건해 20년 남짓 된 사찰이다. 역사는 짧지만 길상사를 찾는 이들에게 전해지는 이야기가 많다.
  길상사는 원래 대원각이라는 요정이었다. 고급 요릿집이 절집으로 탈바꿈한 데는 법정 스님과 김영한의 이야기가 있다. 법정 스님은 1932년 전남 해남에서 태어나 1956년 효봉 스님의 제자로 출가했으며, 2010년 길상사에서 입적했다.','https://cdn.ilyoseoul.co.kr/news/photo/202108/456307_375351_4051.jpg, https://cdn.ilyoseoul.co.kr/news/photo/202108/456307_375349_3935.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (59,'정릉',17,6,'서울 성북구 아리랑로 19길 116','  조선 1대 태조의 두 번째 왕비 신덕황후 강씨(?~1396)의 능이다.
  신덕황후는 강윤성의 딸로 고려의 풍습에 따라 태조의 경처(서울에서 결혼한 부인)가 되었다가, 1392년 조선 건국 후 최초의 왕비(현비)로 책봉되었다. 둘째아들 방석을 왕세자로 책봉시켜 정치적 기반을 닦았으나 이 일로 왕자의 난이 일어나 정치적으로 혼란하였다. 태조는 신덕황후가 세상을 떠나자 현 서울 중구 정동에 조성하였으나, 태종이 왕위에 오른 후 1409년(태종 9) 도성 안에 능이 있다는 이유로 도성 밖 현재의 자리에 옮겼고, 남아있던 목재와 석물을 태평관太平館과 청계천 광통교 복구에 사용하였으며, 태조의 왕비로 인정하지 않았다. 1669년(현종 10) 송시열 등의 상소로 신주를 종묘에 모시고, 정릉을 현재의 모습으로 다시 조성하였다.
  능침은 추존된 왕비의 능제에 맞게 조성되어 병풍석과 난간석, 무석인을 생략하고 문석인과 석양, 석호 등을 배치하였다. 장명등과 혼유석을 받치는 고석만 옛 정릉에서 옮겨온 석물이고 나머지 석물들은 현종대에 다시 조성하였다. 이후 1899년(광무 3) 신덕고황후로 추존되었다.','http://www.heritage.go.kr/unisearch/images/history_site/2020081411085900.jpg, http://www.heritage.go.kr/unisearch/images/history_site/2021070715063000.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (60,'석촌호수 야경',18,5,'서울 송파구 삼학사로 136','롯데월드 타워 및 롯데월드 근처에 위치한 호수로 호수 위로 펼쳐진 화려한 야경이 특징','https://mapio.net/images-p/13904888.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (61,'백제고분군',18,6,'서울 송파구 오금로 219','  서울 방이동 일대에 있는 백제전기(4C초∼475)의 무덤들이다.
  제1호 무덤은 봉토의 지름이 12m, 높이 2.2m로 널길(연도)과 널방(현실)을 가진 굴식돌방무덤(횡혈식석실분)이다. 도굴로 인해 남아 있는 유물이 없었으나, 주민에 의해 3접의 토기가 수습되었다. 4호 무덤은 아치형천장(궁륭식천장)을 한 굴식돌방무덤으로, 자연적으로 유약이 입혀진 회청색경질 굽다리접시(고배)와 굽다리접시뚜껑을 비롯한 토기류와 철제류가 출토되었다.
  6호 무덤에서 나온 회청색경질 굽다리접시의 경우 굽구멍(투창)이 전형적인 신라토기에서 볼 수 있는 형식이다. 이는 6세기 이후 한강유역이 신라영토로 되었을 때 만들어진 신라무덤일 가능성도 있다.
  방이동 고분군은 백제의 수도가 한성에 있을 때 만들어진 전기 무덤으로 가락동·석촌동무덤과 함께 한성백제의 문화를 알 수 있는 유적이다.','http://www.heritage.go.kr/unisearch/images/history_site/1624838.jpg, http://www.heritage.go.kr/unisearch/images/history_site/1624840.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (62,'롯데호텔월드',18,10,'서울 송파구 올림픽로 240','송파구에 위치한 5성급 호텔, 롯데월드
바로 앞에 위치해있어 호캉스에 용이하다','http://drive.google.com/uc?export=view&id=1g23fc04wTXEvVchJOhvFswplWNs5bB_q');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (63,'서울책보고',18,7,'서울 송파구 오금로1 (신천동14)','서울시가 헌책방들을 모아 새로 만든 서울 헌책방','https://pds.joongang.co.kr/news/component/joongang_sunday/201904/27/5a22bae4-798a-46ad-b5e6-259232412119.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (64,'서울둘레길 6코스',19,4,'서울 양천구 신정동','본 코스는 다소 길지만 지하철역이 곳곳에 위치하고 있어 대중교통의 접근이 편리하고 
전 구간이 평탄한 지형으로 수월한 트레킹이 가능하다.','https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FB5KLF%2Fbtq1IRhwuuN%2FWkPqoZV7IPTFqw3p8AwsCk%2Fimg.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (65,'카멜리온',19,8,'서울 양천구 오목로 196 1층','SBS 생방송투데이에 방영된 카페 멜론빵 맛집','https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=https%3A%2F%2Fmyplace-phinf.pstatic.net%2F20210801_208%2F1627818904536JpJxk_JPEG%2Fupload_4d853b5078a246a30145a83b44ff7588.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (66,'여의도공원',20,4,'서울 영등포구 여의공원로 68 (우)07243','활주로가 있던 자리에 문을 연 여의도공원은 다양한 행사와 휴식의 여가를 즐길 수 있는 문화공간입니다','http://parks.seoul.go.kr/images/egovframework/com/template/yeouido1.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (67,'63전망대 야경',20,5,'서울 영등포구 63로 50','서울의 상징적인 랜드마크 중 하나인 63빌딩에 위치한 전망대로 경치 뿐만 아니라 현대 미술 작품들을 감상 가능함','https://mblogthumb-phinf.pstatic.net/20150214_255/avnet75_1423874818667ysVFR_JPEG/008.JPG?type=w2');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (68,'선유도 공원 야경',20,5,'서울 영등포구 선유로 343','우리나라 최초의 재활용 생태 공원,','https://cdn.crowdpic.net/list-thumb/thumb_l_0FE32A6276E052E847372AD89788CDB1.jpeg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (69,'여의도 한강공원',20,1,'서울 영등포구 여의도 여의서로(윤중로)','꽂구경과 운치 있는 한강 변을 구경하기에 좋다','http://drive.google.com/uc?export=view&id=1TSVkX8f2vvsXSYg8vPH3hh-yGA3e1f2d');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (70,'선유도 공원',20,1,'서울 영등포구 선유로 343 (당산동, 선유도공원)','우리나라 최초의 재활용 생태공원','http://drive.google.com/uc?export=view&id=1BUnbQ5Efi-UWKMEPAFZLucSEB7PpqrXY');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (71,'슈치쿠',20,3,'서울 영등포구 63로 50 58층',' 신선한 재료의 맛을 살린 스시와 사시미를 맛볼 수 있다.','https://drive.google.com/uc?export=view&id=1DW_4120C_agkZPxpzjTN5iA0U-EuoXku');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (72,'하쯔호',20,3,'서울 영등포구 여의동로 213 지하1층','코스 외에 단품도 여러 가지 준비되어 있다. ','https://drive.google.com/uc?export=view&id=1CgA-S0kAeQBifLmDo9HybQqruskTTiAG');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (73,'욥',20,8,'서울 영등포구 당산로44길 3 삼성타운','여의도 유명한 빵집 브래드핏과 브래드랩의 총괄셰프였던 임용순 셰프가 새롭게 개업한 카페, 화학 첨가제 사용x, 저녁 8시까지 영업','https://modo-phinf.pstatic.net/20160623_217/1466664757044RiUcE_JPEG/mosaAlmEWl.jpeg?type=w720');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (74,'글래드 호텔 여의도',20,10,'서울 영등포구 의사당대로 16','서울 영등포구에 위치한 4성급 호텔','http://drive.google.com/uc?export=view&id=1bZ_E21TgR7EhzoRhoMTQ1Wj6QnvFXZC5');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (75,'남산서울타워 야경',21,5,'서울 용산구 남산공원길 105','유명 드라마 및 예능에 자주 등장하는 서울을 대표하는 한류 명소 중 하나','http://www.travelnbike.com/news/photo/201603/18544_17674_14.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (76,'국립중앙박물관',21,6,'서울 용산구 서빙고로 137','시대와 주제별로 제시된 6개의 상설전시관, 다양한 내용을 선보이는 특별전시관, 관람의 이해를 돕는 전시해설 프로그램, 오감으로 즐기고 배우는 어린이박물관, 다채로운 교육 프로그램, 첨단기술을 활용한 실감콘텐츠 등을 마음껏 누리고 즐길 수 있다.','http://www.heritage.go.kr/unisearch/images/national_treasure/2021092813404100.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (77,'페트라',21,3,' 서울 용산구 녹사평대로40길 33','시리아와 요르단 음식을 내는 곳으로, 아랍 음식을 맛볼 수 있다.','https://drive.google.com/uc?export=view&id=1IuurSXCZio49pgf_lJLLWxkoqtDEKxND');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (78,'널담은공간',21,8,'서울 용산구 신흥로15길 18-12','365개의 보관함에 편지와 엽서등을 써서 원하는 날짜에 자신, 친구, 연인 그리고 소중한 사람에게 편지와 엽서 발송가능,
1층의 메인공간, 2층의 편안한 공간, 3층의 루프탑까지','https://www.nuldam.com/web/upload/goodymall/kr_mobile/201020_%ED%99%88%ED%8E%98%EC%9D%B4%EC%A7%80_%EB%B8%8C%EB%9E%9C%EB%93%9C_%EB%84%90%EB%8B%B4%EA%B3%B5%EA%B0%84_%EC%82%AC%EC%A7%843.png');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (79,'그랜드하얏트서울 그랜드캠핑',21,9,'서울 용산구 소월로 322 그랜드 하얏트 서울','그랜드하얏트 호텔 앞쪽에 위치한 가족친화적
캠핑장이다, 어린아이들을 위한 시설이 많다','http://drive.google.com/uc?export=view&id=1Qfrn0DYFApeUWk070_FTsRlCmqiGjzTF');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (80,'불광천',22,4,'서울 은평구 응암동','옛이름 연신내였던 불광천은 사계절 맑은 물이 흐르는 하천이며 현재 서울의 명품관광지로 추진중이다','https://img.seoul.co.kr//img/upload/2019/03/25/SSI_20190325171712_V.jpgVzyND5AJe2Eg.xzC84JevsSlfKyoCraRIQz5LCE7KLY9Zx1TB1hPIEfwg.JPEG.spacedot96/KakaoTalk_20210607_235126606_04.jpg?type=w773');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (81,'HUGA',22,8,'서울 은평구 진관2로 19 3층 휴가','"나는 쉰다. 그러므로 가치있다" 모토로 편안한 쉼터와 아름다움을 추구하는 카페','https://modo-phinf.pstatic.net/20190227_181/15512346289533Q1xu_JPEG/mosakVNkNI.jpeg?type=w720');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (82,'서울북한산글램핑',22,9,'서울특별시 은평구 진관동 330-14','글램핑 컨셉의 캠핑장','http://drive.google.com/uc?export=view&id=1DQ0v5sT-ObAQFprtW80IQXg-sMPnp_Bj');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (83,'청계천',23,4,'서울 종로구 서린동 148','서울의 한복판인 종로구와 중구와의 경계를 흐르는 하천이며 야경명소와 데이트 코스로 자주 언급 됨','https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA5MDlfMjQ3%2FMDAxNjMxMTk1NzEzNDUw.BcV7dmGcSf8WvUK92MxoBz9Z5AJA2lGHE2Vn4bnoIEMg.E7-dN4NwoB0xkjBkYmZSc7MS5N6AvgdReKx2qptOiNog.JPEG.tazumi27%2Foutput_955599499.jpg&type=sc960_832');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (84,'광화문광장 야경',23,5,'서울시 종로구 세종대로 172','서울특별시 종로구 광화문에서 세종로사거리와 청계광장으로 이어지는 세종로 중앙에 조성된 광장, 600년 역사를 지닌 서울의 중심거리 세종로를 차량 중심에서 인간 중심의 공간으로 전환하고, 경복궁과 북악산 등 아름다운 자연경관 조망 공간으로 새롭게 조성, 현재 재구조화중','https://gwanghwamun.seoul.go.kr/mcms/upload/encoding/image/2021/08/MIG_PT_PH_00000608002.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (85,'낙산공원 야경',23,5,'서울특별시 종로구 낙산길 41','성곽을 따라 걸으며 산책과 함께 서울의 야경을 즐길 수 있는 야경 조망 명소','https://mediahub.seoul.go.kr/wp-content/uploads/2016/01/cab8f2cc78869c71093fe215305065c7.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (86,'북악산 야경',23,5,'서울 종로구 부암동','1.21 사태로 출입이 금지되었다가 나중에 개방된 산으로 정상에 있는 팔각정에서 서울 시내의 야경을 구경 가능','http://www.travelnbike.com/news/photo/201811/70216_122089_5755.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (87,'경복궁',23,6,'서울 종로구 사직로 161','  경복궁은 조선 왕조 제일의 법궁이다. 북으로 북악산을 기대어 자리 잡았고 정문인 광화문 앞으로는 넓은 육조거리(지금의 세종로)가 펼쳐져, 왕도인 한양(서울) 도시 계획의 중심이기도 하다. 1395년 태조 이성계가 창건하였고, 1592년 임진 왜란으로 불타 없어졌다가, 고종 때인 1867년 중건 되었다. 흥선대원군이 주도한 중건 경복궁은 500여 동의 건물들이 미로같이 빼곡히 들어선 웅장한 모습 이었다.
  궁궐 안에는 왕과 관리들의 정무 시설, 왕족들의 생활 공간, 휴식을 위한 후원 공간이 조성되었다. 또한 왕비의 중궁, 세자의 동궁, 고종이 만든 건청궁 등 궁궐안에 다시 여러 작은 궁들이 복잡하게 모인 곳이기도 하다. 그러나 일제 강점기에 거의 대부분의 건물들을 철거하여 근정전 등 극히 일부 중심 건물만 남았고, 조선 총독부 청사를 지어 궁궐 자체를 가려버렸다. 
  다행히 1990년부터 본격적인 복원 사업이 추진되어 총독부 건물을 철거하고 흥례문 일원을 복원하였으며, 왕과 왕비의 침전, 동궁, 건청궁, 태원전 일원의 모습을 되찾고 있다.광화문 - 흥례문 - 근정문 - 근정전 - 사정전 - 강녕전 - 교태전을 잇는 중심 부분은 궁궐의 핵심 공간이며, 기하학적 질서에 따라 대칭적으로 건축 되었다. 
  그러나 중심부를 제외한 건축물들은 비대칭적으로 배치되어 변화와 통일의 아름다움을 함께 갖추었다. 수도 서울의 중심이고 조선의 으뜸 궁궐인 경복궁에서 격조 높고 품위 있는 왕실 문화의 진수를 느껴보자.
  경복궁의 명칭 : 경복궁은 조선 왕조가 세워지고 3년 지난 후 완공되었다. 완공된 지 며칠 후에 개국공신 정도전은 태조의명에 따라 경복궁이라는 궁궐 이름을 비롯해 강녕전, 교태전, 연생전, 경성전, 사정전, 근정전 등 주요 전각의 이름을 지었다. 경복궁이라는 이름에는 ‘새 왕조가 큰 복을 누려 번영할 것’이라는 의미가 담겨 있다.','http://www.heritage.go.kr/unisearch/images/national_treasure/2021062917265903.jpg, http://www.heritage.go.kr/unisearch/images/national_treasure/1611714.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (88,'북악산',23,2,'서울 종로구 부암동','서울 경복궁 북쪽에 솟아 그 진산을 이루어온 산','http://drive.google.com/uc?export=view&id=1_WTALwqYJFXFDWRHj2wAVGhfbjPTNVty');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (89,'낙산',23,2,'서울 종로구 창신동','성곽을 따라 산책도 하고 서울의 야경을 즐길 수 있는 산','http://drive.google.com/uc?export=view&id=1eVRM1MqiWmctMH1vXZjdVNJbZOBy03aq');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (90,'인왕산',23,2,'서울 종로구 무악동 산2-1','정상에서 경복궁을 중심으로 내산,남산,백악산을 한 눈에 볼 수 있음','http://drive.google.com/uc?export=view&id=1JzImKxogt2r6Obg8dnDXvDjJDRpsWwE-');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (91,'낙산공원',23,1,'서울 종로구 낙산길 41','쾌적한 공원경관 제공, 자연탐방을 통해 역사와 문화교육의 장을 제공','http://drive.google.com/uc?export=view&id=1i3DUhkJcWFN2m9fdNJ4OyfOqMtX6n87R');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (92,'지화자',23,3,'서울 종로구 자하문로 125','서울의 중심부에 위치하는 고급 한식당','http://drive.google.com/uc?export=view&id=1fUeqOAQrPNBgts5ed5Qt-i8OMKOqq9tY');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (93,'중국',23,3,' 서울 종로구 자하문로33길 2','짬뽕, 짜장면, 탕수육 등이 맛있는 집으로 소문났다.','https://drive.google.com/uc?export=view&id=1rm3Edh_EjbAx1rZnGCFq_KTH6jFIKYPU');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (94,'페르시안궁전',23,3,' 서울 종로구 성균관로6길 9 ','이란식 매운 커리 전문점.','https://drive.google.com/uc?export=view&id=1ySg0VVZ7fDwQhipZyjMSnBNG1ChHxS4I');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (95,'호면당',23,3,' 서울 종로구 새문안로 91 ','현대적인 인테리어의 퓨전음식점','https://drive.google.com/uc?export=view&id=11wwgehD1gAzhQwcm1a8MWoXK3qbJvFS0');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (96,'마지',23,3,'서울시 종로구 자하문로5길 19  ','한국전통채식을 바탕으로 파, 마늘등의 자극적인 재료를 사용하지 않은 웰빙채식 식단이다.','https://drive.google.com/uc?export=view&id=1VbJSUTCYrPJYg0SMtszbLYTarrQTC_B_');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (97,'오세계향',23,3,'서울 종로구 인사동12길 14-5','동물성, GMO 원재료, MSG를 사용하지 않은 비건채식 레스토랑이다.','https://drive.google.com/uc?export=view&id=1mo-fSP4yJxfmokT-CLH-XebkB0MQZiSU');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (98,'산촌',23,3,'서울 종로구 인사동길 30-13',' 산나물과 신선한 채소 바다에서 나오는 해초류등을 사용한 사찰음식','https://drive.google.com/uc?export=view&id=1vxTtn45FF64GtmB0xCjv5vBQaTmDOXEF');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (99,'한과채',23,3,'서울 종로구 인사동10길 13 ','한과채는 2004년 개업한 완전 채식식당이다.','http://drive.google.com/uc?export=view&id=1K2Ju5qP5q5RKPQudOq9XrQYrm6ePQm77');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (100,'포시즌스 호텔 서울',23,10,'서울 종로구 새문안로 97','서울 종로구에 위치한 5성급 호텔','http://drive.google.com/uc?export=view&id=1xMxDvPlByje7pOyK0borpw-zKtKyZO8O');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (101,'종묘',23,6,'서울 종로구 종로 157','  종묘는 조선왕조 역대 왕과 왕비 및 추존된 왕과 왕비의 신주를 모신 유교사당으로서 가장 정제되고 장엄한 건축물 중의 하나이다.
  야트막한 산과 숲에 둘러싸여 있으며, 역대 왕과 왕비의 신주를 모신 정전과 영녕전, 제례 준비에 필요한 몇몇 부속 전각으로 이루어졌다. 전각은 최소한의 색만 사용하고 화려한 단청을 하지 않았으며 장식과 기교를 최대한 절제하였다. 이는 종묘가 조상신의 영혼을 모신 엄숙하고 경건한 공간이기 때문이다.
  태조 3년(1394) 10월 조선 왕조가 한양으로 도읍을 옮긴 그해 12월에 착공하여 이듬해 9월에 완공 하였으며, 곧이어 개성으로부터 태조의 4대조인 목조, 익조, 도조, 환조의 신주를 모셨다. 현재 정전에는 19실에 49위, 영녕전에는 16실에 34위의 신위가 모셔져 있고, 정전 뜰앞에 있는 공신당에는 조선시대 공신 83위가 모셔져 있다.','http://www.heritage.go.kr/unisearch/images/national_treasure/2021063016361203.jpg, http://www.heritage.go.kr/unisearch/images/treasure/2021070117175901.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (102,'창경궁',23,6,'서울특별시 종로구 와룡동 창경궁로 185','  창경궁은 경복궁, 창덕궁에 이어 세 번째로 지어진 조선시대 궁궐이다. 조선 왕조는 건국 초기부터 경복궁을 법궁으로, 창덕궁을 보조 궁궐로 사용하는 양궐 체제를 이어왔다. 그러나 역대 왕들은 경복궁보다는 창덕궁에 거처하는 것을 더 좋아하였고, 왕실 가족이 늘어나면서 차츰 창덕궁의 생활 공간도 비좁아졌다. 이에 성종이 왕실의 웃어른인 세조 비 정희왕후, 예종 비 안순왕후, 덕종 비 소혜왕후 등 세 분의 대비가 편히 지낼 수 있도록 창덕궁 이웃에 마련한 궁궐이 창경궁이다.
  창경궁은 왕이 정사를 돌보기 위해 지은 것이 아니라 생활 공간을 넓힐 목적으로 세워졌고, 또한 애초 궁궐로서 계획된 것이 아니라 태종이 세종에게 왕위를 물려준 뒤 살았던 수강궁에 몇몇 전각을 보태어 세운 궁궐이다. 따라서 경복궁이나 창덕궁과 비교해볼 때 그 규모나 배치 등에 다른 점이 많다.
  우선 창경궁은 전각의 수가 많지 않고 규모가 아담하다. 공간의 구조와 배치도 경복궁처럼 평지에 일직선의 축을 이루도록 구획된 것이 아니라 창덕궁처럼 높고 낮은 지세를 거스르지 않고 언덕과 평지를 따라가며 터를 잡아 필요한 전각을 지었기에 좀 더 자유로운 분위기이다. 정조가 어머니 혜경궁 홍씨를 위해 지은 자경전도 언덕에 지어졌다.
  창경궁의 또 다른 독특함은 조선시대 다른 궁궐과 주요 전각들이 남향으로 지어진 것과 달리 동쪽을 바라보고 있는 점이다. 창경궁의 경우 정문인 홍화문과 정전인 명정전은 동쪽을 향하고, 관청 건물인 궐내각사와 내전의 주요 전각들은 남쪽을 향해 있다. 남·서·북쪽이 구릉이고, 동쪽이 평지인 지세라서 이를 거스르지 않았기 때문인 것으로 짐작된다.','http://www.heritage.go.kr/unisearch/images/national_treasure/1611760.jpg, http://www.heritage.go.kr/unisearch/images/national_treasure/2021063016231203.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (103,'창덕궁',23,6,'서울 종로구 율곡로 99','  창덕궁은 1405년 (태종5년) 조선왕조의 이궁으로 지어진 궁궐이다.
  경복궁의 동쪽에 자리한 창덕궁은 창경궁과 더불어 동궐이라 불리기도 했다. 임진왜란으로 모든 궁궐이 불에 타자 선조는 경복궁이 아닌 창덕궁의 복구를 선조 40년(1607)에 시작하였으며, 창덕궁은 광해군 2년(1610)에 중건이 마무리 되었다.
  그 후 창덕궁은 1623년 3월 인조반정으로 인정전을 제외하고 또다시 불에 타는 시련을 겪는다. 인조 25년(1647)에 복구되었으나 크고 작은 화재가 이후에도 여러 차례 반복되었다. 특히 1917년 대조전을 중심으로 내전 일곽이 손실되는 대화재가 일어났다. 이때 창덕궁을 복구하기 위하여 경복궁 내의 교태전을 비롯한 강녕전 동·서행각 등의 건물이 해체 전용되었다.
  창덕궁은 1610년 광해군때부터 1868년 고종이 경복궁을 중건할 때가지 총 258년 동안 조선의 궁궐 중 가장 오랜 기간 동안 임금들이 거처하며 정사를 편 궁궐이다.
  조선시대의 뛰어난 조경을 보여주는 창덕궁의 후원을 통해 궁궐의 조경양식을 알 수 있다. 후원에는 160여 종의 나무들이 있으며, 그 중에는 300년이 넘는 나무도 있어 원형이 비교적 충실히 보존되어 있음을 알 수 있다. 창덕궁은 조선시대의 조경이 훼손되지 않고 지금까지 잘 보존되어 있는 귀중한 장소이다.','http://www.heritage.go.kr/unisearch/images/history_site/2021070616362901.jpg, http://www.heritage.go.kr/unisearch/images/history_site/2021070616363002.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (104,'마음책방 서가는',23,7,'서울 종로구 창경궁로 35길 21','심리와 치유서를 주로 출간하는 생각속의집에서 만든 심리 전문 책방','https://scontent-gmp1-1.xx.fbcdn.net/v/t1.18169-9/26196343_1160675057398481_6242793497591114089_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=8bfeb9&_nc_ohc=PQZJzMnJLK4AX8GzFEp&_nc_ht=scontent-gmp1-1.xx&oh=4dfa16172e1839417ca8000a1101aee1&oe=6189C6B3');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (105,'보안책방',23,7,'서울 종로구 효자로 33','60년간 여관으로 운영되었다가 문화예술공간으로 변신한 보안여관 내에 존재하는 책방','https://www.visitseoul.net/comm/getImage?srvcId=MEDIA&parentSn=27450&fileTy=MEDIA&fileNo=1');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (106,'이라선',23,7,'서울 종로구 효자로7길 5','전형적인 서점 분위기에 탈피해 ''집 안의 서재''를 모티브로 한 사진 전문 서점','https://image.elle.co.kr/upload/NEWS/2018/03/ncd_031510590/20180315_112433604_31524.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (107,'매봉산 야경',24,5,'서울특별시 중구 신당동 산51','성동구와 용산구에 걸쳐있는 산으로 남산과 연결되어 산책로 겸 관광 목적으로 자주 사용되는 야경 명소','https://cdn.crowdpic.net/list-thumb/thumb_l_63BB871CACFD256A9DD0F61993571432.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (108,'남산골 한옥마을',24,6,'서울 중구 퇴계로34길 28','  남산 북쪽 기슭 한옥마을이 들어선 필동(筆洞)은 조선시대 흐르는 계곡이 있어 여름철 피서를 겸한 풍류생활로 이름난 곳이었다. 서울시는 시내에 산재되어 있던 민속문화재 한옥 다섯 채를 이전 · 복원하여 1998년 4월 18일 남산골한옥마을을 조성하고, 선조들의 생활모습을 재조명할 수 있는 전통문화 예술공간으로 꾸몄다. 한옥의 공간적 가치를 살려 시민과 관광객들이 전통문화를 체험할 수 있는 다양한 행사와 프로그램을 진행하고 있다. 
  또한 훼손되었던 남산의 옛 자연지형을 전통정원으로 복원하여 남산의 자연식생인 전통 수종을 심고, 계곡을 만들어 물이 흐르게 하였다. 연못과 정자도 복원되어 선조들이 유유자적하였던 남산의 옛 정취를 한껏 느낄 수 있다. 1994년에 서울을 도읍으로 정한 ‘서울 정도(定都) 600년’을 맞이하여, 서울의 모습과 시민들의 생활을 대표하는 문물 600점을 보신각종 모양의 캡슐에 담아 전통정원 남쪽에 매장하였다, 서울천년타임캡슐은 정도(定都) 1,000년이 되는 2394년 11월 29일에 개봉될 예정이다.','http://www.heritage.go.kr/unisearch/images/folklore_material/1658059.jpg, http://www.heritage.go.kr/unisearch/images/folklore_material/2016012510460300.JPG, http://www.heritage.go.kr/unisearch/images/folklore_material/2016012510460306.JPG');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (109,'숭례문',24,6,'서울 중구 세종대로 40','  조선시대 한양도성의 정문으로 남쪽에 있다고 해서 남대문이라고도 불렀다. 현재 서울에 남아 있는 목조 건물 중 가장 오래된 것으로 태조 5년(1396)에 짓기 시작하여 태조 7년(1398)에 완성하였다. 이 건물은 세종 30년(1448)에 고쳐 지은 것인데 1961∼1963년 해체·수리 때 성종 10년(1479)에도 큰 공사가 있었다는 사실이 밝혀졌다. 이후, 2008년 2월 10일 숭례문 방화 화재로 누각 2층 지붕이 붕괴되고 1층 지붕도 일부 소실되는 등 큰 피해를 입었으며, 5년 2개월에 걸친 복원공사 끝에 2013년 5월 4일 준공되어 일반에 공개되고 있다.
  이 문은 돌을 높이 쌓아 만든 석축 가운데에 무지개 모양의 홍예문을 두고, 그 위에 앞면 5칸·옆면 2칸 크기로 지은 누각형 2층 건물이다. 지붕은 앞면에서 볼 때 사다리꼴 형태를 하고 있는데, 이러한 지붕을 우진각지붕이라 한다. 지붕 처마를 받치기 위해 기둥 위부분에 장식하여 짠 구조가 기둥 위뿐만 아니라 기둥 사이에도 있는 다포 양식으로, 그 형태가 곡이 심하지 않고 짜임도 건실해 조선 전기의 특징을 잘 보여주고 있다.
   『지봉유설』의 기록에는 ‘숭례문’이라고 쓴 현판을 양녕대군이 썼다고 한다. 지어진 연대를 정확히 알 수 있는 서울 성곽 중에서 제일 오래된 목조 건축물이다.
  ㅇ 숭례문 방화 화재(2008.2.10)
  - 2008년 숭례문 방화 사건(崇禮門放火事件)은 2008년 2월 10일 ~ 2월 11일 숭례문 건물이 방화로 타 무너진 사건이다. 화재는 2008년 2월 10일 오후 8시 40분 전후에 발생하여 다음날인 2008년 2월 11일 오전 0시 40분경 숭례문의 누각 2층 지붕이 붕괴하였고 이어 1층에도 불이 붙어 화재 5시간 만인 오전 1시 55분쯤 석축을 제외한 건물이 훼손되었다.','http://www.heritage.go.kr/unisearch/images/national_treasure/2021042017434802.JPG, http://www.heritage.go.kr/unisearch/images/national_treasure/2685703.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (110,'남산',24,2,'서울 중구 회현동1가','서울의 대표적인 산으로 멋진 야경과 즐길거리가 많음','http://drive.google.com/uc?export=view&id=1ajJNG8kBRxXJha6xDo3O4QgT0zLHUVQ3');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (111,'매봉산',24,2,'서울 중구 신당동  매봉산 공원','서울 10대 야경 명소 중 하나','http://drive.google.com/uc?export=view&id=1cB99akNuaiF-OAR4GfYQyQGzEbHxozod');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (112,'덕수궁',24,6,'서울 중구 세종대로 99','  덕수궁은 조선시대를 통틀어 크게 두 차례 궁궐로 사용되었다. 덕수궁이 처음 궁궐로 사용 된 것은 임진왜란 때 피난 갔다 돌아온 선조가 머물 궁궐이 마땅치 않아 월산대군의 집이었던 이곳을 임시 궁궐(정릉동 행궁)로 삼으면서 부터이다. 이후 광해군이 창덕궁으로 옮겨가면서 정릉동 행궁에 새 이름을 붙여 경운궁이라고 불렀다. 경운궁이 다시 궁궐로 사용된 것은 조선 말기 러시아 공사관에 있던 고종이 이곳으로 옮겨 오면서부터이다.
  덕수궁의 독특한 건물은 다수 남아 있다. 함녕전 뒤편에 있는 정관헌은 전통식 지붕 구조와 서양식 기둥 양식이 절충된 건물이다. 석조전은 내부와 외부가 모두 서양식으로 꾸며진 건물이다. 이처럼 덕수궁에 여러 서양식 건물이 남아 있는 것을 통해 고종이 서구 문물을 적극적으로 도입한 점을 알 수 있다.
  현재 덕수궁 권역은 고종 당시의 궁궐 면모에는 크게 못 미치지만, 덕수궁에는 저마다 사연을 안은 유서 깊은 전각들이 오순도순 자리하고 있다. 석어당에서 석조전에 이르는 뒤쪽에는 도심의 번잡함을 잊게 하는 호젓한 산책로도 있다. 파란만장한 근대사의 자취를 기억하는 덕수궁은 서울에서 손꼽히는 산책로인 정동길과 더불어 도심의 직장인과 연인들에게 사랑받고 있다.','http://www.heritage.go.kr/unisearch/images/history_site/2021070809303201.jpg, http://www.heritage.go.kr/unisearch/images/history_site/2021070809303502.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (113,'남산공원',24,1,'서울 중구 삼일대로 231','서울에 있는 공원중 가장 넓은 공원, 다양한 문화행사','http://drive.google.com/uc?export=view&id=1BhEA-kZf1EPkEShl-stFsevwhzN-F9Mc');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (114,'동보성',24,3,'서울 중구 퇴계로18길 5','중국의 광동 및 사천요리를 우리입맛에 맞게 하는 곳이다.','https://drive.google.com/uc?export=view&id=197zcmFx9jVe5iDaHvUkmROar--wOY-B3');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (115,'그랜드 앰배서더 서울 어소시에이티드 풀만 호텔',24,10,'서울 중구 동호로 287','서울 중구에 위치한 5성급 호텔','http://drive.google.com/uc?export=view&id=1SBxhpkSTV3dpz1OHMjjChx-sdyGOhIfs');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (116,'나인트리 호텔 명동',24,10,'서울 중구 명동10길 51','서울 중구에 위치한 3성급 호텔','http://drive.google.com/uc?export=view&id=1HQOYYZ042gKlbHAPTaAwQ7mxRQRUKL7k');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (117,'롯데호텔 서울',24,10,'서울 중구 을지로 30','서울 중구에 위치한 5성 호텔','http://drive.google.com/uc?export=view&id=1PpYGQ_-HLKU5uJlaEmvupwF49UNidelc');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (118,'피제이 호텔 명동',24,10,'서울 중구 마른내로 71','서울 중구에 위치한 4성급 호텔, 가성비 호캉스
로 좋음','http://drive.google.com/uc?export=view&id=1jQqOHfBCiZ5Eiu1wFDPZJZah-TpQnM8i');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (119,'서울 책방',24,7,'서울 중구 세종대로 110 지하1층','서울 관련 도서와 서울시가 만든 책자를 자유롭게 열람하고 구매 가능한 공간','http://image.chosun.com/sitedata/image/201408/31/2014083100391_0.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (120,'청계천 헌책방 거리',24,7,'서울 중구 장충단로 13길 20','약 20여개의 헌 책방이 모여 있는 거리','https://dimg.donga.com/ugc/CDB/SHINDONGA/Article/5d/ba/2e/51/5dba2e510db3d2738de6.jpg');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (121,'용마 폭포공원',25,1,'서울 중랑구 용마산로 250-12','용마산을 등산하면서 폭포의 시원함을 만끽할 수 있음','http://drive.google.com/uc?export=view&id=1O3AscilPMw0OH9QirBIlNcZbJ4HQb5uN');
INSERT INTO TRAVEL (TRAVELNO,TRAVELNAME,LOCALCODE,THEMECODE,ADDRESS,DESCRIPTION,URL_PIC) VALUES (122,'중랑캠핑숲',25,9,'서울 중랑구 망우로87길 110','중랑구에 위치한 숲 컨셉의 캠핑장','http://drive.google.com/uc?export=view&id=1HvKC5j_UPijReL_KXla2He9AFFiJS-3f');
=======
SELECT * FROM LOCATION;
>>>>>>> branch 'master' of https://github.com/junmipark/Uravel_TeamProject.git
