CREATE TABLE "TRAVEL" (
  "TRAVELNO" NUMBER,
  "TRAVELNAME" VARCHAR2(100),
  "LOCALCODE" NUMBER REFERENCES LOCATION(LOCALCODE),
  "THEMECODE" NUMBER REFERENCES THEME(THEMECODE),
  "ADDRESS" VARCHAR2(500) NOT NULL,
  "DESCRIPTION" VARCHAR2(1000) NOT NULL,
  "URL_PIC" VARCHAR2(1000),
  PRIMARY KEY ("TRAVELNO", "TRAVELNAME")
);

DROP TABLE TRAVEL;