DELETE FROM MEMBER;
DROP SEQUENCE memberseq;

CREATE SEQUENCE memberseq;
INSERT INTO "MEMBER" VALUES(memberseq.nextval,'ADMIN','ADMIN','관리자', SYSDATE,'ADMIN@URAVEL.COM',NULL,'ADMIN', DEFAULT);
INSERT INTO "MEMBER" VALUES(MEMBERSEQ.NEXTVAL, 'USER1', 'PASSWORD', '유저1', SYSDATE, 'USER1@URAVEL.COM', NULL, 'USER', DEFAULT);
INSERT INTO "MEMBER" VALUES(MEMBERSEQ.NEXTVAL, 'USER2', 'PASSWORD', '유저2', SYSDATE, 'USER2@URAVEL.COM', NULL, 'USER', DEFAULT);

CREATE TABLE SOCIAL_MEMBER (
  USERID VARCHAR2(20) REFERENCES MEMBER(USERID), 
  SOCIAL_TYPE VARCHAR2(2) CHECK(SOCIAL_TYPE IN('K','N'))
);

SELECT * FROM MEMBER;
SELECT * FROM SOCIAL_MEMBER;

INSERT INTO DW."MEMBER" (USERNO,USERID,USERPW,USERNAME,BIRTH,EMAIL,PHONE,"ROLE",ENABLED) VALUES (3,'USER2','PASSWORD','유저2','21/10/27','USER2@URAVEL.COM',NULL,'USER','Y');
INSERT INTO DW."MEMBER" (USERNO,USERID,USERPW,USERNAME,BIRTH,EMAIL,PHONE,"ROLE",ENABLED) VALUES (4,'USER3','PASSWORD','유저3','21/10/27','USER3@URAVEL.COM',NULL,'USER','N');
INSERT INTO DW."MEMBER" (USERNO,USERID,USERPW,USERNAME,BIRTH,EMAIL,PHONE,"ROLE",ENABLED) VALUES (1,'ADMIN','ADMIN','관리자','21/10/27','ADMIN@URAVEL.COM',NULL,'ADMIN','Y');
INSERT INTO DW."MEMBER" (USERNO,USERID,USERPW,USERNAME,BIRTH,EMAIL,PHONE,"ROLE",ENABLED) VALUES (2,'USER1','PASSWORD','유저1','21/10/27','USER1@URAVEL.COM',NULL,'USER','Y');
INSERT INTO DW."MEMBER" (USERNO,USERID,USERPW,USERNAME,BIRTH,EMAIL,PHONE,"ROLE",ENABLED) VALUES (5,'USER4','PASSWORD','유저4','21/10/27','USER4@URAVEL.COM',NULL,'USER','N');

UPDATE MEMBER SET BIRTH = NULL;
ALTER TABLE MEMBER MODIFY BIRTH VARCHAR2(8);
INSERT INTO MEMBER VALUES(1, '1234ABCD','USER1','김민서',SYSDATE,'123@GMAIL.COM','010-1234-5678','USER', 'Y');






