DROP TABLE MEMBER;
DROP TABLE SOCIAL_MEMBER;

CREATE TABLE MEMBER (
  USERNO NUMBER,
  USERID VARCHAR2(20),
  USERPW VARCHAR2(20) NOT NULL,
  USERNAME VARCHAR2(50) NOT NULL,
  BIRTH DATE,
  EMAIL VARCHAR2(100) NOT NULL,
  PHONE VARCHAR2(20),
  ROLE VARCHAR2(10) CHECK(ROLE IN ('ADMIN','USER')),
  ENABLED VARCHAR2(2) CHECK(ENABLED IN('Y','N')),
  PRIMARY KEY(USERNO), UNIQUE(USERID)
);

CREATE TABLE SOCIAL_MEMBER (
  USERID VARCHAR2(20) REFERENCES MEMBER(USERID), 
  SOCIAL_TYPE VARCHAR2(2) CHECK(SOCIAL_TYPE IN('K','N'))
);

SELECT * FROM MEMBER;
SELECT * FROM SOCIAL_MEMBER;
