DELETE FROM MEMBER;
DROP SEQUENCE memberseq;

CREATE SEQUENCE memberseq NOCACHE;

CREATE TABLE "MEMBER" (
   "USERNO" NUMBER, 
   "USERID" VARCHAR2(20), 
   "USERPW" VARCHAR2(20) NOT NULL ENABLE, 
   "USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
   "BIRTH" VARCHAR2(8), 
   "EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
   "PHONE" VARCHAR2(20), 
   "ROLE" VARCHAR2(10), 
   "ENABLED" VARCHAR2(2) DEFAULT 'Y', 
    CHECK (ROLE IN ('ADMIN','USER')) ENABLE, 
    CHECK (ENABLED IN('Y','N')) ENABLE, 
    PRIMARY KEY ("USERNO")
)

ALTER TABLE MEMBER MODIFY ENABLED DEFAULT 'Y';

INSERT INTO "MEMBER" VALUES(memberseq.nextval,'ADMIN','ADMIN','관리자', SYSDATE,'ADMIN@URAVEL.COM',NULL,'ADMIN', DEFAULT);
INSERT INTO "MEMBER" VALUES(MEMBERSEQ.NEXTVAL, 'USER1', 'PASSWORD', '유저1', SYSDATE, 'USER1@URAVEL.COM', NULL, 'USER', DEFAULT);
INSERT INTO "MEMBER" VALUES(MEMBERSEQ.NEXTVAL, 'USER2', 'PASSWORD', '유저2', SYSDATE, 'USER2@URAVEL.COM', NULL, 'USER', DEFAULT);

CREATE TABLE SOCIAL_MEMBER (
  USERID VARCHAR2(20) REFERENCES MEMBER(USERID), 
  SOCIAL_TYPE VARCHAR2(2) CHECK(SOCIAL_TYPE IN('K','N'))
);

SELECT * FROM MEMBER;
SELECT * FROM SOCIAL_MEMBER;


ALTER TABLE MEMBER MODIFY BIRTH VARCHAR2(30);
INSERT INTO MEMBER VALUES(1, '1234ABCD','USER1','김민서',SYSDATE,'123@GMAIL.COM','010-1234-5678','USER', 'Y');


