drop table weatherkr;

-- WEATHERKR definition

CREATE TABLE "WEATHERKR" 
   (	"ID" VARCHAR2(4000), 
	"DESCRIPTION" VARCHAR2(4000), 
	"KOREAN" VARCHAR2(4000)
   );

INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('200','thunderstorm with light rain','가벼운 비를 동반한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('201','thunderstorm with rain','비를 동반한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('202','thunderstorm with heavy rain','폭우를 동반한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('210','light thunderstorm','약한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('211','thunderstorm','천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('212','heavy thunderstorm','강한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('221','ragged thunderstorm','불규칙적 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('230','thunderstorm with light drizzle','약한 연무를 동반한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('231','thunderstorm with drizzle','연무를 동반한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('232','thunderstorm with heavy drizzle','강한 안개비를 동반한 천둥구름');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('300','light intensity drizzle','가벼운 안개비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('301','drizzle','안개비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('302','heavy intensity drizzle','강한 안개비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('310','light intensity drizzle rain','가벼운 적은비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('311','drizzle rain','적은비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('312','heavy intensity drizzle rain','강한 적은비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('313','shower rain and drizzle','소나기와 안개비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('314','heavy shower rain and drizzle','강한 소나기와 안개비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('321','shower drizzle','소나기');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('500','light rain','약한 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('501','moderate rain','중간 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('502','heavy intensity rain','강한 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('503','very heavy rain','매우 강한 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('504','extreme rain','극심한 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('511','freezing rain','우박');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('520','light intensity shower rain','약한 소나기 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('521','shower rain','소나기 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('522','heavy intensity shower rain','강한 소나기 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('531','ragged shower rain','불규칙적 소나기 비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('600','light snow','가벼운 눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('601','snow','눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('602','heavy snow','강한 눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('611','sleet','진눈깨비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('612','shower sleet','소나기 진눈깨비');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('615','light rain and snow','약한 비와 눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('616','rain and snow','비와 눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('620','light shower snow','약한 소나기 눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('621','shower snow','소나기 눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('622','heavy shower snow','강한 소나기 눈');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('701','mist','박무');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('711','smoke','연기');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('721','haze','연무');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('731','sand, dust whirls','모래 먼지');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('741','fog','안개');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('751','sand','모래');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('761','dust','먼지');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('762','volcanic ash','화산재');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('771','squalls','돌풍');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('781','tornado','토네이도');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('800','clear sky','구름 한 점 없는 맑은 하늘');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('801','few clouds','약간의 구름이 낀 하늘');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('802','scattered clouds','드문드문 구름이 낀 하늘');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('803','broken clouds','구름이 거의 없는 하늘');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('804','overcast clouds','구름으로 뒤덮인 흐린 하늘');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('900','tornado','토네이도');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('901','tropical storm','태풍');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('902','hurricane','허리케인');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('903','cold','한랭');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('904','hot','고온');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('905','windy','바람부는');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('906','hail','우박');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('951','calm','바람이 거의 없는');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('952','light breeze','약한 바람');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('953','gentle breeze','부드러운 바람');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('954','moderate breeze','중간 세기 바람');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('955','fresh breeze','신선한 바람');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('956','strong breeze','센 바람');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('957','high win','돌풍에 가까운 센 바람');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('958','gale','돌풍');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('959','severe gale','심각한 돌풍');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('960','storm','폭풍');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('961','violent storm','강한 폭풍');
INSERT INTO WEATHERKR (ID,DESCRIPTION,KOREAN) VALUES ('962','hurricane','허리케인');

COMMIT;

SELECT * FROM WEATHERKR;
